services:
  db:
    container_name: db_container
    image: mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      retries: 5
    restart: on-failure
  
    volumes:
      -  db_data:/var/lib/mysql
      -  ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  web:
    container_name: node_app_container
    build:
      context: ./frontend
  backend:
    container_name: backend_container
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
       condition: service_healthy
      
  nginx:
    container_name: nginx_reverseproxy_container
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - '80:80'
    depends_on: 
      - backend
volumes:
  db_data:
